[build-system]
requires = ["poetry-core>=1.9.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[project]
name = "pydanfossally"
dynamic = ["version"]
description = "Danfoss Ally API library"
readme = "README.md"
license = "MIT"
authors = [{ name = "Malene Trab", email = "malene@trab.dk" }]
requires-python = ">=3.9,<4.0"
dependencies = ["aiohttp>=3.13.0,<4.0.0"]

[project.urls]
Homepage = "https://github.com/mtrab/pydanfossally"
Repository = "https://github.com/mtrab/pydanfossally"

[tool.poetry]
packages = [{ include = "pydanfossally" }]
version = "0.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
strict = true
